/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RolesUsersModel model module.
 * @module model/RolesUsersModel
 * @version 0.1.0
 */
class RolesUsersModel {
    /**
     * Constructs a new <code>RolesUsersModel</code>.
     * @alias module:model/RolesUsersModel
     * @param userId {Number} 
     * @param roleId {Number} 
     */
    constructor(userId, roleId) { 
        
        RolesUsersModel.initialize(this, userId, roleId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userId, roleId) { 
        obj['user_id'] = userId;
        obj['role_id'] = roleId;
    }

    /**
     * Constructs a <code>RolesUsersModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RolesUsersModel} obj Optional instance to populate.
     * @return {module:model/RolesUsersModel} The populated <code>RolesUsersModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RolesUsersModel();

            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('role_id')) {
                obj['role_id'] = ApiClient.convertToType(data['role_id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} user_id
 */
RolesUsersModel.prototype['user_id'] = undefined;

/**
 * @member {Number} role_id
 */
RolesUsersModel.prototype['role_id'] = undefined;






export default RolesUsersModel;

