/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RoleModelAll model module.
 * @module model/RoleModelAll
 * @version 0.1.0
 */
class RoleModelAll {
    /**
     * Constructs a new <code>RoleModelAll</code>.
     * @alias module:model/RoleModelAll
     */
    constructor() { 
        
        RoleModelAll.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RoleModelAll</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RoleModelAll} obj Optional instance to populate.
     * @return {module:model/RoleModelAll} The populated <code>RoleModelAll</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RoleModelAll();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
RoleModelAll.prototype['id'] = undefined;

/**
 * @member {String} name
 */
RoleModelAll.prototype['name'] = undefined;

/**
 * @member {String} description
 */
RoleModelAll.prototype['description'] = undefined;






export default RoleModelAll;

