/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RoleModel from './RoleModel';

/**
 * The UserModelAll model module.
 * @module model/UserModelAll
 * @version 0.1.0
 */
class UserModelAll {
    /**
     * Constructs a new <code>UserModelAll</code>.
     * @alias module:model/UserModelAll
     */
    constructor() { 
        
        UserModelAll.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserModelAll</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserModelAll} obj Optional instance to populate.
     * @return {module:model/UserModelAll} The populated <code>UserModelAll</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserModelAll();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('middle_name')) {
                obj['middle_name'] = ApiClient.convertToType(data['middle_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('date_registerd')) {
                obj['date_registerd'] = ApiClient.convertToType(data['date_registerd'], 'Date');
            }
            if (data.hasOwnProperty('disabled')) {
                obj['disabled'] = ApiClient.convertToType(data['disabled'], 'Boolean');
            }
            if (data.hasOwnProperty('roles')) {
                obj['roles'] = ApiClient.convertToType(data['roles'], [RoleModel]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
UserModelAll.prototype['id'] = undefined;

/**
 * @member {String} uid
 */
UserModelAll.prototype['uid'] = undefined;

/**
 * @member {String} email
 */
UserModelAll.prototype['email'] = undefined;

/**
 * @member {String} username
 */
UserModelAll.prototype['username'] = undefined;

/**
 * @member {String} first_name
 */
UserModelAll.prototype['first_name'] = undefined;

/**
 * @member {String} middle_name
 */
UserModelAll.prototype['middle_name'] = undefined;

/**
 * @member {String} last_name
 */
UserModelAll.prototype['last_name'] = undefined;

/**
 * @member {String} password
 */
UserModelAll.prototype['password'] = undefined;

/**
 * @member {Date} date_registerd
 */
UserModelAll.prototype['date_registerd'] = undefined;

/**
 * @member {Boolean} disabled
 */
UserModelAll.prototype['disabled'] = undefined;

/**
 * @member {Array.<module:model/RoleModel>} roles
 */
UserModelAll.prototype['roles'] = undefined;






export default UserModelAll;

