/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('addUserRolesAdminAddrolesPost', function() {
      it('should call addUserRolesAdminAddrolesPost successfully', function(done) {
        //uncomment below and update the code to test addUserRolesAdminAddrolesPost
        //instance.addUserRolesAdminAddrolesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAllRolesAdminRoleAllDelete', function() {
      it('should call deleteAllRolesAdminRoleAllDelete successfully', function(done) {
        //uncomment below and update the code to test deleteAllRolesAdminRoleAllDelete
        //instance.deleteAllRolesAdminRoleAllDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAllUserAdminUserAllDelete', function() {
      it('should call deleteAllUserAdminUserAllDelete successfully', function(done) {
        //uncomment below and update the code to test deleteAllUserAdminUserAllDelete
        //instance.deleteAllUserAdminUserAllDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteRoleAdminRoleItemIdDelete', function() {
      it('should call deleteRoleAdminRoleItemIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteRoleAdminRoleItemIdDelete
        //instance.deleteRoleAdminRoleItemIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUserAdminUserItemUuidDelete', function() {
      it('should call deleteUserAdminUserItemUuidDelete successfully', function(done) {
        //uncomment below and update the code to test deleteUserAdminUserItemUuidDelete
        //instance.deleteUserAdminUserItemUuidDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUserRolesAdminDeleterolesRoleIdUserIdDelete', function() {
      it('should call deleteUserRolesAdminDeleterolesRoleIdUserIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteUserRolesAdminDeleterolesRoleIdUserIdDelete
        //instance.deleteUserRolesAdminDeleterolesRoleIdUserIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllRolesAdminRolesAllGet', function() {
      it('should call getAllRolesAdminRolesAllGet successfully', function(done) {
        //uncomment below and update the code to test getAllRolesAdminRolesAllGet
        //instance.getAllRolesAdminRolesAllGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllUsersAdminUsersAllGet', function() {
      it('should call getAllUsersAdminUsersAllGet successfully', function(done) {
        //uncomment below and update the code to test getAllUsersAdminUsersAllGet
        //instance.getAllUsersAdminUsersAllGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRoleAdminRoleItemIdGet', function() {
      it('should call getRoleAdminRoleItemIdGet successfully', function(done) {
        //uncomment below and update the code to test getRoleAdminRoleItemIdGet
        //instance.getRoleAdminRoleItemIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserAdminUserItemUuidGet', function() {
      it('should call getUserAdminUserItemUuidGet successfully', function(done) {
        //uncomment below and update the code to test getUserAdminUserItemUuidGet
        //instance.getUserAdminUserItemUuidGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('indexGet', function() {
      it('should call indexGet successfully', function(done) {
        //uncomment below and update the code to test indexGet
        //instance.indexGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('loginTokenAdminTokenPost', function() {
      it('should call loginTokenAdminTokenPost successfully', function(done) {
        //uncomment below and update the code to test loginTokenAdminTokenPost
        //instance.loginTokenAdminTokenPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('loginUserAdminLoginPost', function() {
      it('should call loginUserAdminLoginPost successfully', function(done) {
        //uncomment below and update the code to test loginUserAdminLoginPost
        //instance.loginUserAdminLoginPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registerRolesAdminRoleRegisterPost', function() {
      it('should call registerRolesAdminRoleRegisterPost successfully', function(done) {
        //uncomment below and update the code to test registerRolesAdminRoleRegisterPost
        //instance.registerRolesAdminRoleRegisterPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registerUserAdminUserRegisterPost', function() {
      it('should call registerUserAdminUserRegisterPost successfully', function(done) {
        //uncomment below and update the code to test registerUserAdminUserRegisterPost
        //instance.registerUserAdminUserRegisterPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('testOauth2AdminTestoauthGet', function() {
      it('should call testOauth2AdminTestoauthGet successfully', function(done) {
        //uncomment below and update the code to test testOauth2AdminTestoauthGet
        //instance.testOauth2AdminTestoauthGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateRoleAdminRoleupdateItemIdPut', function() {
      it('should call updateRoleAdminRoleupdateItemIdPut successfully', function(done) {
        //uncomment below and update the code to test updateRoleAdminRoleupdateItemIdPut
        //instance.updateRoleAdminRoleupdateItemIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUserAdminUserroleItemUuidPut', function() {
      it('should call updateUserAdminUserroleItemUuidPut successfully', function(done) {
        //uncomment below and update the code to test updateUserAdminUserroleItemUuidPut
        //instance.updateUserAdminUserroleItemUuidPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
